import { createDb, schema } from '../src/index.js';

const db = createDb(process.env.DATABASE_URL ?? 'postgresql://lexia:lexia@localhost:5432/lexia_dev');

const questions = [
  // --- CONSTITUCIÓN (10) ---
  {
    questionText: '¿En qué año fue aprobada la Constitución Española?',
    options: ['1975', '1977', '1978', '1980'],
    correctOption: 2,
    category: 'constitucion',
    difficulty: 'easy',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 1',
  },
  {
    questionText: '¿Cuántos artículos tiene la Constitución Española?',
    options: ['100', '128', '155', '169'],
    correctOption: 3,
    category: 'constitucion',
    difficulty: 'medium',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 1',
  },
  {
    questionText: '¿Cuál es la forma política del Estado español según la Constitución?',
    options: ['República federal', 'Monarquía absoluta', 'Monarquía parlamentaria', 'República parlamentaria'],
    correctOption: 2,
    category: 'constitucion',
    difficulty: 'easy',
    verifiedByHuman: false,
    source: 'Constitución Española, art. 1.3',
  },
  {
    questionText: '¿Qué reconoce el artículo 14 de la Constitución Española?',
    options: ['El derecho a la educación', 'La libertad de expresión', 'La igualdad ante la ley', 'El derecho al trabajo'],
    correctOption: 2,
    category: 'constitucion',
    difficulty: 'medium',
    verifiedByHuman: false,
    source: 'Constitución Española, art. 14',
  },
  {
    questionText: '¿Cuál es el idioma oficial en todo el territorio español?',
    options: ['El catalán', 'El gallego', 'El vasco', 'El castellano'],
    correctOption: 3,
    category: 'constitucion',
    difficulty: 'easy',
    verifiedByHuman: false,
    source: 'Constitución Española, art. 3',
  },
  {
    questionText: '¿Qué órgano es el máximo intérprete de la Constitución Española?',
    options: ['El Tribunal Supremo', 'El Consejo de Estado', 'El Tribunal Constitucional', 'El Defensor del Pueblo'],
    correctOption: 2,
    category: 'constitucion',
    difficulty: 'medium',
    verifiedByHuman: false,
    source: 'Constitución Española, art. 123',
  },
  {
    questionText: '¿Cuántos títulos tiene la Constitución Española además del Título Preliminar?',
    options: ['8', '9', '10', '12'],
    correctOption: 2,
    category: 'constitucion',
    difficulty: 'hard',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 1',
  },
  {
    questionText: '¿Qué establece el artículo 1.1 de la Constitución sobre el Estado español?',
    options: ['La soberanía del Rey', 'España como Estado social y democrático de Derecho', 'La neutralidad religiosa del Estado', 'La división de poderes'],
    correctOption: 1,
    category: 'constitucion',
    difficulty: 'medium',
    verifiedByHuman: false,
    source: 'Constitución Española, art. 1.1',
  },
  {
    questionText: '¿Quién puede proponer la reforma de la Constitución Española?',
    options: ['Solo el Gobierno', 'Solo el Senado', 'Las Cortes Generales, el Gobierno y las Asambleas de las CCAA', 'El Rey a propuesta del Tribunal Supremo'],
    correctOption: 2,
    category: 'constitucion',
    difficulty: 'hard',
    verifiedByHuman: false,
    source: 'Constitución Española, art. 166',
  },
  {
    questionText: '¿Cuándo se celebra el Día de la Constitución Española?',
    options: ['23 de abril', '12 de octubre', '6 de diciembre', '25 de julio'],
    correctOption: 2,
    category: 'constitucion',
    difficulty: 'easy',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 1',
  },
  // --- GOBIERNO (10) ---
  {
    questionText: '¿Cómo se denomina el órgano legislativo del Estado español?',
    options: ['El Consejo de Ministros', 'El Tribunal Supremo', 'Las Cortes Generales', 'El Consejo de Estado'],
    correctOption: 2,
    category: 'gobierno',
    difficulty: 'easy',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 2',
  },
  {
    questionText: '¿Cuáles son las dos cámaras que forman las Cortes Generales?',
    options: ['La Asamblea Nacional y el Senado', 'El Congreso de los Diputados y el Senado', 'El Congreso y el Tribunal Supremo', 'La Cámara Alta y la Cámara de Representantes'],
    correctOption: 1,
    category: 'gobierno',
    difficulty: 'easy',
    verifiedByHuman: false,
    source: 'Constitución Española, art. 66',
  },
  {
    questionText: '¿Cuántos diputados tiene el Congreso de los Diputados?',
    options: ['200', '250', '350', '400'],
    correctOption: 2,
    category: 'gobierno',
    difficulty: 'medium',
    verifiedByHuman: false,
    source: 'Constitución Española, art. 68',
  },
  {
    questionText: '¿Quién nombra al Presidente del Gobierno en España?',
    options: ['El Congreso directamente', 'El Tribunal Constitucional', 'El Rey, a propuesta del Congreso', 'Los ciudadanos en elección directa'],
    correctOption: 2,
    category: 'gobierno',
    difficulty: 'medium',
    verifiedByHuman: false,
    source: 'Constitución Española, art. 99',
  },
  {
    questionText: '¿Cómo se llama el jefe del Estado en España?',
    options: ['El Presidente del Gobierno', 'El Presidente del Congreso', 'El Rey', 'El Presidente del Senado'],
    correctOption: 2,
    category: 'gobierno',
    difficulty: 'easy',
    verifiedByHuman: false,
    source: 'Constitución Española, art. 56',
  },
  {
    questionText: '¿Cuántos años dura una legislatura ordinaria en España?',
    options: ['2 años', '3 años', '4 años', '5 años'],
    correctOption: 2,
    category: 'gobierno',
    difficulty: 'easy',
    verifiedByHuman: false,
    source: 'Constitución Española, art. 68',
  },
  {
    questionText: '¿Qué es el Defensor del Pueblo?',
    options: ['El presidente del Tribunal Supremo', 'Un ministro del Interior', 'Un comisionado de las Cortes para defender los derechos ciudadanos', 'El Fiscal General del Estado'],
    correctOption: 2,
    category: 'gobierno',
    difficulty: 'medium',
    verifiedByHuman: false,
    source: 'Constitución Española, art. 54',
  },
  {
    questionText: '¿Qué función tiene el Tribunal de Cuentas?',
    options: ['Resolver recursos de casación', 'Fiscalizar las cuentas y la gestión económica del sector público', 'Asesorar al Gobierno en materias legales', 'Gestionar la deuda pública'],
    correctOption: 1,
    category: 'gobierno',
    difficulty: 'hard',
    verifiedByHuman: false,
    source: 'Constitución Española, art. 136',
  },
  {
    questionText: '¿Dónde está la sede de la Presidencia del Gobierno de España?',
    options: ['El Palacio Real', 'El Congreso de los Diputados', 'El Palacio de la Moncloa', 'El Palacio de Oriente'],
    correctOption: 2,
    category: 'gobierno',
    difficulty: 'easy',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 2',
  },
  {
    questionText: '¿Qué es el Consejo de Estado?',
    options: ['El órgano máximo del poder ejecutivo', 'El supremo órgano consultivo del Gobierno', 'El órgano de control del poder judicial', 'La cámara de coordinación territorial'],
    correctOption: 1,
    category: 'gobierno',
    difficulty: 'hard',
    verifiedByHuman: false,
    source: 'Constitución Española, art. 107',
  },
  // --- TERRITORIO (10) ---
  {
    questionText: '¿Cuántas comunidades autónomas tiene España?',
    options: ['15', '16', '17', '19'],
    correctOption: 2,
    category: 'territorio',
    difficulty: 'easy',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 3',
  },
  {
    questionText: '¿Cuántas provincias tiene España?',
    options: ['40', '47', '50', '52'],
    correctOption: 2,
    category: 'territorio',
    difficulty: 'medium',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 3',
  },
  {
    questionText: '¿Cuál es la comunidad autónoma más extensa de España?',
    options: ['Andalucía', 'Castilla y León', 'Castilla-La Mancha', 'Aragón'],
    correctOption: 1,
    category: 'territorio',
    difficulty: 'medium',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 3',
  },
  {
    questionText: '¿Cuántas ciudades autónomas tiene España?',
    options: ['1', '2', '3', '4'],
    correctOption: 1,
    category: 'territorio',
    difficulty: 'medium',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 3',
  },
  {
    questionText: '¿Cuál es la comunidad autónoma más poblada de España?',
    options: ['Madrid', 'Cataluña', 'Andalucía', 'Valencia'],
    correctOption: 2,
    category: 'territorio',
    difficulty: 'medium',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 3',
  },
  {
    questionText: '¿Qué son los Estatutos de Autonomía?',
    options: ['Las leyes que regulan los municipios', 'Los reglamentos del Senado', 'Las normas institucionales básicas de cada comunidad autónoma', 'Los decretos del Gobierno central'],
    correctOption: 2,
    category: 'territorio',
    difficulty: 'medium',
    verifiedByHuman: false,
    source: 'Constitución Española, art. 147',
  },
  {
    questionText: '¿En qué mar está bañada la costa este de España?',
    options: ['El Mar del Norte', 'El Océano Atlántico', 'El Mar Mediterráneo', 'El Mar Cantábrico'],
    correctOption: 2,
    category: 'territorio',
    difficulty: 'easy',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 3',
  },
  {
    questionText: '¿Con qué país comparte España la mayor parte de la Península Ibérica?',
    options: ['Francia', 'Italia', 'Portugal', 'Marruecos'],
    correctOption: 2,
    category: 'territorio',
    difficulty: 'easy',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 3',
  },
  {
    questionText: '¿Cuál es la cadena montañosa que separa España de Francia?',
    options: ['La Cordillera Cantábrica', 'El Sistema Ibérico', 'Los Pirineos', 'Sierra Nevada'],
    correctOption: 2,
    category: 'territorio',
    difficulty: 'easy',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 3',
  },
  {
    questionText: '¿Cuál es el río más caudaloso de España?',
    options: ['El Tajo', 'El Duero', 'El Ebro', 'El Guadalquivir'],
    correctOption: 2,
    category: 'territorio',
    difficulty: 'medium',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 3',
  },
  // --- HISTORIA (10) ---
  {
    questionText: '¿En qué año comenzó la transición a la democracia en España?',
    options: ['1973', '1974', '1975', '1977'],
    correctOption: 2,
    category: 'historia',
    difficulty: 'easy',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 4',
  },
  {
    questionText: '¿Cuándo se celebraron las primeras elecciones democráticas en España tras el franquismo?',
    options: ['1975', '1976', '1977', '1978'],
    correctOption: 2,
    category: 'historia',
    difficulty: 'medium',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 4',
  },
  {
    questionText: '¿Quién fue el primer presidente del Gobierno de la democracia española?',
    options: ['Felipe González', 'Leopoldo Calvo-Sotelo', 'Adolfo Suárez', 'Manuel Fraga'],
    correctOption: 2,
    category: 'historia',
    difficulty: 'medium',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 4',
  },
  {
    questionText: '¿En qué año entró España en la Comunidad Económica Europea?',
    options: ['1982', '1984', '1986', '1989'],
    correctOption: 2,
    category: 'historia',
    difficulty: 'medium',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 4',
  },
  {
    questionText: '¿Qué ocurrió en España el 23 de febrero de 1981?',
    options: ['Se firmó la Constitución', 'España ingresó en la OTAN', 'Un intento de golpe de Estado', 'Felipe González ganó las elecciones'],
    correctOption: 2,
    category: 'historia',
    difficulty: 'medium',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 4',
  },
  {
    questionText: '¿Cuándo tuvo lugar la Guerra Civil española?',
    options: ['1930-1933', '1934-1937', '1936-1939', '1939-1945'],
    correctOption: 2,
    category: 'historia',
    difficulty: 'easy',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 4',
  },
  {
    questionText: '¿En qué siglo se unieron los Reinos de Castilla y Aragón con los Reyes Católicos?',
    options: ['XIV', 'XV', 'XVI', 'XVII'],
    correctOption: 1,
    category: 'historia',
    difficulty: 'medium',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 4',
  },
  {
    questionText: '¿Qué rey reinaba en España antes de la proclamación de la Segunda República?',
    options: ['Carlos III', 'Fernando VII', 'Alfonso XIII', 'Alfonso XII'],
    correctOption: 2,
    category: 'historia',
    difficulty: 'hard',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 4',
  },
  {
    questionText: '¿En qué año se proclamó la Segunda República española?',
    options: ['1928', '1929', '1930', '1931'],
    correctOption: 3,
    category: 'historia',
    difficulty: 'medium',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 4',
  },
  {
    questionText: '¿Qué conquista marcó el fin de la Reconquista en 1492?',
    options: ['La toma de Sevilla', 'La batalla de Covadonga', 'La conquista de Granada', 'La toma de Toledo'],
    correctOption: 2,
    category: 'historia',
    difficulty: 'medium',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 4',
  },
  // --- SOCIEDAD (10) ---
  {
    questionText: '¿Cuántos habitantes tiene España aproximadamente?',
    options: ['35 millones', '40 millones', '47 millones', '55 millones'],
    correctOption: 2,
    category: 'sociedad',
    difficulty: 'easy',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 5',
  },
  {
    questionText: '¿Cuál es la moneda oficial de España?',
    options: ['La peseta', 'El franco', 'El euro', 'La libra'],
    correctOption: 2,
    category: 'sociedad',
    difficulty: 'easy',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 5',
  },
  {
    questionText: '¿En qué año adoptó España el euro como moneda de curso legal?',
    options: ['1999', '2002', '2004', '2007'],
    correctOption: 1,
    category: 'sociedad',
    difficulty: 'medium',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 5',
  },
  {
    questionText: '¿Qué celebra España el 12 de octubre?',
    options: ['La Constitución', 'La muerte de Franco', 'La Fiesta Nacional (Día de la Hispanidad)', 'El fin de la Guerra Civil'],
    correctOption: 2,
    category: 'sociedad',
    difficulty: 'easy',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 5',
  },
  {
    questionText: '¿Cuál es el pico más alto de todo el territorio español?',
    options: ['El Mulhacén', 'El Aneto', 'El Teide', 'La Maladeta'],
    correctOption: 2,
    category: 'sociedad',
    difficulty: 'medium',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 5',
  },
  {
    questionText: '¿Quién escribió "Don Quijote de la Mancha"?',
    options: ['Federico García Lorca', 'Lope de Vega', 'Francisco de Quevedo', 'Miguel de Cervantes'],
    correctOption: 3,
    category: 'sociedad',
    difficulty: 'easy',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 5',
  },
  {
    questionText: '¿Quién pintó el cuadro "Las Meninas"?',
    options: ['Francisco Goya', 'El Greco', 'Diego Velázquez', 'Joan Miró'],
    correctOption: 2,
    category: 'sociedad',
    difficulty: 'easy',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 5',
  },
  {
    questionText: '¿Cuál es el premio literario de mayor prestigio en lengua española?',
    options: ['El Premio Planeta', 'El Premio Nobel', 'El Premio Cervantes', 'El Premio Nacional de las Letras'],
    correctOption: 2,
    category: 'sociedad',
    difficulty: 'medium',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 5',
  },
  {
    questionText: '¿En qué ciudad española está la Sagrada Familia?',
    options: ['Madrid', 'Valencia', 'Sevilla', 'Barcelona'],
    correctOption: 3,
    category: 'sociedad',
    difficulty: 'easy',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 5',
  },
  {
    questionText: '¿Cuál es la festividad más importante de la Semana Santa española?',
    options: ['El Viernes de Dolores', 'El Domingo de Ramos', 'El Viernes Santo', 'El Domingo de Resurrección'],
    correctOption: 3,
    category: 'sociedad',
    difficulty: 'medium',
    verifiedByHuman: false,
    source: 'Manual CCSE, Bloque 5',
  },
];

async function seed() {
  console.log(`Insertando ${questions.length} preguntas CCSE...`);
  await db.insert(schema.ccseQuestions).values(questions);
  console.log('Seed completado.');
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
